In [45]:
import pandas as pd

df = pd.read_csv('D:/EliteML-End-to-End-House-Price-Prediction-with-MLOps/Extracted_Data/AmesHousing.csv')

In [46]:
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [47]:
df.isnull().sum()

Order               0
PID                 0
MS SubClass         0
MS Zoning           0
Lot Frontage      490
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 82, dtype: int64

In [58]:
numerical_features = df.select_dtypes(include=['int','float']).columns

In [67]:
df_cleaned = df.copy()
df_cleaned[numerical_features] = df[numerical_features].fillna(df[numerical_features].mean())

In [68]:
from sklearn.preprocessing import StandardScaler
df_cleaned[['Gr Liv Area','SalePrice']] = StandardScaler().fit_transform(df[['Gr Liv Area','SalePrice']])

In [69]:
import numpy as np
threshold = 3
df_numeric = df_cleaned.select_dtypes(include=['int',"float"])
zscore = np.abs((df_numeric-df_numeric.mean())/df_numeric.std())
outliers = zscore> threshold

In [70]:
df_cleaned = df_cleaned[(~outliers).all(axis=1)]
df_cleaned

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1,2,526350040,20,RH,80.00000,11622,Pave,NaN,Reg,Lvl,...,120,0,MnPrv,NaN,0,6,2010,WD,Normal,-0.948957
3,4,526353030,20,RL,93.00000,11160,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,0,4,2010,WD,Normal,0.791305
4,5,527105010,60,RL,74.00000,13830,Pave,NaN,IR1,Lvl,...,0,0,MnPrv,NaN,0,3,2010,WD,Normal,0.113980
5,6,527105030,60,RL,78.00000,9978,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,0,6,2010,WD,Normal,0.184091
6,7,527127150,120,RL,41.00000,4920,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,0,4,2010,WD,Normal,0.409449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2923,2924,923250060,20,RL,80.00000,17400,Pave,NaN,Reg,Low,...,0,0,NaN,NaN,0,5,2006,WD,Normal,-0.260364
2925,2926,923275080,80,RL,37.00000,7937,Pave,NaN,IR1,Lvl,...,0,0,GdPrv,NaN,0,3,2006,WD,Normal,-0.479462
2926,2927,923276100,20,RL,69.22459,8885,Pave,NaN,IR1,Low,...,0,0,MnPrv,NaN,0,6,2006,WD,Normal,-0.623440
2928,2929,924100070,20,RL,77.00000,10010,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,0,4,2006,WD,Normal,-0.135165
2929,2930,924151050,60,RL,74.00000,9627,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,0,11,2006,WD,Normal,0.090192

In [71]:
x = df_cleaned.drop(columns='SalePrice')
y = df_cleaned.SalePrice

In [72]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)

In [75]:
categorical_col = xtrain.select_dtypes(include=['object','category']).columns

In [76]:
categorical_col

Index(['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour',
       'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl',
       'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating', 'Heating QC',
       'Central Air', 'Electrical', 'Kitchen Qual', 'Functional',
       'Fireplace Qu', 'Garage Type', 'Garage Finish', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Fence', 'Misc Feature', 'Sale Type',
       'Sale Condition'],
      dtype='object')